version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - "> 0.82.0"
  - dependency-name: activesupport
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: falcon
    versions:
    - 0.37.2
    - 0.37.3
  - dependency-name: minitest
    versions:
    - 5.14.3
