AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - script/*.rb
    - patches/*.rb
    - vendor/**/*
    - tmp/**/*
    - public/**/*

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/LineLength:
  Max: 180

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Lambda:
  EnforcedStyle: literal

Naming/MethodParameterName:
  AllowedNames:
    - vm
    - hv
    - id
    - dn

Naming/AccessorMethodName:
  Exclude:
    - test/**/*.rb

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

